# Generated by Django 6.0.4 on 2026-04-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminded',
            field=models.BooleanField(default=False),
        ),
    ]
